Update Install APT (CI/CD)

diff --git a/gitlab-ci/test_package.yml b/gitlab-ci/test_package.yml
--- a/gitlab-ci/test_package.yml
+++ b/gitlab-ci/test_package.yml
@@ -1,40 +1,43 @@
 stages:
   - install
+  - notify
 
 variables:
   ANSIBLE_HOST_KEY_CHECKING: 'false'
+  TELEGRAM_BOT_TOKEN: "Create bot: @BotFather -> Start New Bot"
+  TELEGRAM_CHAT_ID: "https://api.telegram.org/bot<YourBOTToken>/getUpdates"
 
 cache:
   paths:
     - .ansible/cache
 
-# install_package_r1:
-#   extends: .install_package_template
-#   variables:
-#     SERVER_LIMIT: 'r1_server'
-#   tags:
-#     - r1.server
-
-# install_package_pc_r1:
-#   extends: .install_package_template
-#   variables:
-#     SERVER_LIMIT: 'r1_pc'
-#   tags:
-#     - pc-r1.server
-
-# install_package_r0:
-#   extends: .install_package_template
-#   variables:
-#     SERVER_LIMIT: 'r0_server'
-#   tags:
-#     - r0.server
-
-install_package_pc_r0:
+install_package_r1:
   extends: .install_package_template
   variables:
-    SERVER_LIMIT: 'r0_pc'
+    SERVER_LIMIT: 'r1_server'
   tags:
-    - pc-r0.server
+    - r1.server
+
+install_package_pc_r1:
+  extends: .install_package_template
+  variables:
+    SERVER_LIMIT: 'r1_pc'
+  tags:
+    - pc-r1.server
+
+install_package_r0:
+  extends: .install_package_template
+  variables:
+    SERVER_LIMIT: 'r0_server'
+  tags:
+    - r0.server
+
+# install_package_pc_r0:
+#   extends: .install_package_template
+#   variables:
+#     SERVER_LIMIT: 'r0_pc'
+#   tags:
+#     - pc-r0.server
 
 # install_package_r2:
 #   extends: .install_package_template
@@ -43,18 +46,63 @@ install_package_pc_r0:
 #   tags:
 #     - r2.server
 
-install_package_pc_r2:
-  extends: .install_package_template
-  variables:
-    SERVER_LIMIT: 'r2_pc'
-  tags:
-    - pc-r2.server
+# install_package_pc_r2:
+#   extends: .install_package_template
+#   variables:
+#     SERVER_LIMIT: 'r2_pc'
+#   tags:
+#     - pc-r2.server
 
 .install_package_template:
   stage: install
   script:
+    - echo "Checking server availability..."
+    - ansible -i ansible/inventory/hosts.ini all -m ping --limit "${SERVER_LIMIT}"
+    - echo "Running Ansible playbook..."
     - ansible-playbook -i ansible/inventory/hosts.ini ansible/all.yml --limit "${SERVER_LIMIT}"
+    - PLAYBOOK_STATUS=$?
+    - |
+      if [ $PLAYBOOK_STATUS -eq 0 ]; then
+        echo "${SERVER_LIMIT} - success" > "${SERVER_LIMIT}_job_status.txt";
+      else
+        echo "${SERVER_LIMIT} - failed" > "${SERVER_LIMIT}_job_status.txt"
+        exit 1;
+      fi
+    - cat "${SERVER_LIMIT}_job_status.txt"
+  artifacts:
+    paths:
+      - "${SERVER_LIMIT}_job_status.txt"
   cache:
     key: "${SERVER_LIMIT}_packages"
     paths:
       - .ansible/cache
+
+notify:
+  stage: notify
+  image: curlimages/curl:latest
+  script:
+    - MESSAGE="Результаты выполнения Ansible playbooks:"
+    - COUNTER=1
+    - |
+      for file in *_job_status.txt; do
+        SERVER=$(cat "$file" | cut -d ' ' -f 1)
+        STATUS=$(cat "$file" | cut -d ' ' -f 3)
+        if [ "$STATUS" == "success" ]; then
+          MESSAGE="${MESSAGE}%0A${COUNTER}) playbook выполнен успешно для ${SERVER}"
+        else
+          MESSAGE="${MESSAGE}%0A${COUNTER}) playbook завершился с ошибкой для ${SERVER}"
+        fi
+        COUNTER=$((COUNTER + 1))
+      done
+    - echo -e "$MESSAGE"
+    - curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" -d "chat_id=$TELEGRAM_CHAT_ID" -d "text=$MESSAGE"
+  dependencies:
+    - install_package_r1
+    - install_package_pc_r1
+    - install_package_r0
+  artifacts:
+    paths:
+      - r1_server_job_status.txt
+      - r1_pc_job_status.txt
+      - r0_server_job_status.txt
+  when: always
